sourceFiles = ['client.cpp'
              ,'config.cpp'
              ,'connection/connection.cpp'
              ,'error.cpp'
              ,'exception.cpp'
	      ,'forkcommand.cpp'
	      ,'glue/botglue.cpp'
	      ,'glue/channelglue.cpp'
	      ,'glue/glue.cpp'
	      ,'glue/gluemanager.cpp'
	      ,'glue/logglue.cpp'
	      ,'glue/messageglue.cpp'
	      ,'glue/regexpglue.cpp'
	      ,'glue/reminderglue.cpp'
	      ,'glue/systemglue.cpp'
	      ,'irc/channel.cpp'
	      ,'irc/message.cpp'
	      ,'irc/prefix.cpp'
              ,'irc/server.cpp'
              ,'lua/lua.cpp'
              ,'lua/luafunction.cpp'
              ,'main.cpp'
	      ,'regexp/regexpmanager.cpp'
	      ,'regexp/regexp.cpp'
	      ,'remindermanager.cpp'
              ,'searchidle.c'
              ,'xml/xmldocument.cpp'
              ,'xml/xmlparsercontext.cpp'
              ,'xml/xmlutil.cpp'
              ]

libFiles = ['boost_filesystem-mt'
           ,'boost_regex-mt'
           ,'boost_thread-mt'
           ,'lua'
           ]

Import('env')

env.Program(target='bot', source = sourceFiles, LIBS=libFiles)

