sourceFiles = ['client.cpp'
              ,'config.cpp'
              ,'connection/connection.cpp'
              ,'connection/namedpipe.cpp'
              ,'error.cpp'
              ,'exception.cpp'
              ,'forkcommand.cpp'
              ,'glue/botglue.cpp'
              ,'glue/channelglue.cpp'
              ,'glue/eventglue.cpp'
              ,'glue/glue.cpp'
              ,'glue/gluemanager.cpp'
              ,'glue/logglue.cpp'
              ,'glue/messageglue.cpp'
              ,'glue/regexpglue.cpp'
              ,'glue/reminderglue.cpp'
              ,'glue/systemglue.cpp'
              ,'irc/channel.cpp'
              ,'irc/ircmessage.cpp'
              ,'irc/ircserver.cpp'
              ,'logging/logger.cpp'
              ,'logging/logmanager.cpp'
              ,'logging/logsink.cpp'
              ,'logging/stdoutsink.cpp'
              ,'lua/lua.cpp'
              ,'lua/luafunction.cpp'
              ,'prefix.cpp'
              ,'regexp/regexpmanager.cpp'
              ,'regexp/regexp.cpp'
              ,'remindermanager.cpp'
              ,'searchidle.c'
              ,'server.cpp'
              ,'xml/xmldocument.cpp'
              ,'xml/xmlparsercontext.cpp'
              ,'xml/xmlutil.cpp'
              ]

botFiles = ['main.cpp'
           ]

testFiles = ['tests/run.cpp'
            ,'tests/connection_test.cpp'
            ,'tests/testserver.cpp'
            ]

libFiles = ['boost_filesystem'
           ,'boost_regex'
           ,'boost_thread'
           ,'boost_date_time'
           ,'boost_system'
           ,'lua5.1'
           ,'icuwrap'
           ,'chardet'
           ,'icuuc'
           ,'xml2'
           ,'pthread'
           ]

testLibFiles = ['cppunit'
               ]

Import('env')

base_objects = env.StaticObject(sourceFiles)

env.Program('bot', botFiles+base_objects, LIBS=libFiles)

#env.Program('unit_tests', testFiles+base_objects, LIBS=libFiles+testLibFiles)
